[global]
upstream = "https://github.com/miekg/gitopper-config"
mount = "/tmp"
keys = [
	{ path = "keys/miek_id_ed25519_gitopper.pub", ro = true },
	{ path = "/local/home/miek/.ssh/id_ed25519_gitopper.pub"},
]

[[services]]
machine = "localhost"
branch = "main"
service = "prometheus"
user = "prometheus"
package = "prometheus"
action = "reload"
dirs = [
	{ local = "/etc/prometheus", link = "prometheus/etc" },
]
