[global]
upstream = "https://github.com/miekg/blah-origin"  # repository where to download from
mount = "/tmp"                                     # directory where to download to, mount+service is used as path

[keys]
path = [
	"keys/miek_id_ed25519_gitopper.pub",
	"/local/home/miek/.ssh/id_ed25519_gitopper.pub",
]

[[services]]
machine = "grafana.atoom.net"
branch = "main"
service = "grafana-server" # as used in systemd
user = "grafana"
package = "grafana"     # as used by package mgmt
action = "restart"      # what to do when files are changed
dirs = [
	{ local = "/etc/grafana", link = "grafana/etc" },
	{ local = "/var/lib/grafana/dashboards", link = "grafana/dashboards" }
]
